### ISSUE TITLE
Lewton vorbis decoder

### ISSUE THREAD

**Issue by est31** [doppioslash/arewegameyet#1]
Suggestion to add my [lewton](https://github.com/est31/lewton) vorbis decoder to http://arewegameyet.com/categories/audio.html .

I dunno if it fits, or that section is more about playback libraries, but if you want to use them, you probably need something to decode the audio to PCM samples as well. Vorbis has been a popular audio format in the past for use in games. Probably the `vorbis` crate is worth adding as well, as its currently a bit faster than my implementation, although its not pure rust.

**Comment by doppioslash** [comment]
@est31 Thanks, added both crates.
I think for the time being the audio crates are few enough, but in the future maybe audio formats could have their own category.

**Comment by est31** [comment]
My crate lewton is pure rust, while the `vorbis` crate consists of bindings to the C library. Maybe change the description for the vorbis crate to "Rust bindings for libvorbis" or something like that?

**Comment by doppioslash** [comment]
Sorry, fixed it now.

**Comment by est31** [comment]
Thanks!
