### ISSUE TITLE
Move to rustgd

### ISSUE THREAD

**Issue by erlend-sh** [doppioslash/arewegameyet#110]
How do you feel about moving this repo to [rustgd](https://github.com/rustgd/) to improve its collaborator coverage?

(I mentioned this in a PM on Internals but I never heard back)

**Comment by doppioslash** [comment]
People can collaborate in here as well.
Just send me pull requests. All PR that have been sent I have accepted.

**Comment by erlend-sh** [comment]
Instead of moving it to rustgd, how about creating a dedicated org for arewegameyet? More and more people are asking for a Rust gamedev working group and I am moving that effort forward together with a handful of other enthusiasts. Part of our agenda is to consolidate some currently separate channels so that multiple people share access and maintainer duties. Lowering the bus factor and such.

For starters these would be:

Twitter
Matrix (plus bridge for Discord et.al.)
Reddit

We want to have a portal to all things Rust gamedev and AWGY is the perfect starting point but we can’t use it as a foundation if the stewardship of the repo can’t be opened up to more people.

**Comment by doppioslash** [comment]
If the wg's still willing to take over arewegameyet, we can go ahead with that.
There's this repo, the hosting (atm it's on S3), and 3 domains: .com, .org, .rs.

**Comment by ozkriff** [comment]
I propose closing this issue and continue the discussion only in #210.

**Comment by doppioslash** [comment]
Ok
