### ISSUE TITLE
All category pages returning 404

### ISSUE THREAD

**Issue by 17cupsofcoffee** [doppioslash/arewegameyet#131]
When I try to go to one of the category pages (e.g. http://arewegameyet.com/categories/engines.html), I'm getting a 404 error:

![image](https://user-images.githubusercontent.com/784533/50377689-a3965c00-0619-11e9-9ef4-4c0c8728cc3a.png)

I think this might have been introduced by #130, as the pages were working a day or two ago when I last looked.

**Comment by 17cupsofcoffee** [comment]
Wait, ignore me - think I was getting some dodgy caching or something, seems to be working now 😅

**Comment by doppioslash** [comment]
Ah, categories are now reached at 
```http://arewegameyet.com/categories/engines/```
rather than
```http://arewegameyet.com/categories/engines.html```
