### ISSUE TITLE
Add Quicksilver

### ISSUE THREAD

**Issue by Luke-Nukem** [doppioslash/arewegameyet#164]
I forked with intention of adding [quicksilver](https://github.com/ryanisaacg/quicksilver) to the list somewhere, but I'm unsure where to, and how to classify it.

It's a bit like an SDL2 writen in Rust I think - so a game dev specific library, not an engine.

**Comment by erlend-sh** [comment]
Quicksilver is already listed in Engines: 
https://github.com/doppioslash/arewegameyet/blob/ba2edad42ebdf6da48ec64c97d2ad5fd64e13a9b/content/categories/engines/data.toml

**Comment by Luke-Nukem** [comment]
Oops sorry, must have skipped right over it.

But having said that, does anyone think there needs to be an extra category? Quicksilver isn't really an engine, any more than SDL2 is an engine.

**Comment by doppioslash** [comment]
In that case, we'd probably also need to separate 2d and 3d frameworks.

**Comment by Luke-Nukem** [comment]
Do you think it would be worth doing?

**Comment by tpltnt** [comment]
Can this issue be closed since quicksilver [is listed](http://arewegameyet.com/categories/engines/#quicksilver) ?
(2D vs. 3D engines warrants a separate issue/ticket)
