### ISSUE TITLE
Honorable mention for euc

### ISSUE THREAD

**Issue by PrototypeNM1** [doppioslash/arewegameyet#166]
[euc](https://github.com/zesterer/euc) is a software renderer which simplifies toying with and debugging shaders. I think it deserves honorable mention in either 3D rendering or Shaders, not because it should ever be included in a game but as a tool to develop ideas which would later be translated to a shading language.

**Comment by doppioslash** [comment]
Nice! Added in ef63b1df6d2f502b63688159064a9cc9c53c835d.
