### ISSUE TITLE
Add Tweek - a tween animation kit

### ISSUE THREAD

**Issue by ozkriff** [doppioslash/arewegameyet#171]
- https://www.reddit.com/r/rust_gamedev/comments/awipmu/introducing_tweek_a_tween_animation_kit
- https://medium.com/@hughlang/introducing-tweek-a-tween-animation-kit-for-rust-7d6f1ce7503d
- https://github.com/wasm-network/tweek-rust

**Comment by doppioslash** [comment]
Added in  45c72a6c91439e8e53256491acb6153987a24f1b.

**Comment by johanlindfors** [comment]
Not 100% certain, but the github.com/wasm-network/tweek-rust isn't working anymore, it might have been moved to: https://github.com/scalarwaves/tweek-rust
