### ISSUE TITLE
Add crate: fbxcel-dom

### ISSUE THREAD

**Issue by lo48576** [doppioslash/arewegameyet#173]
Please add crate to category: 3dformatloaders

Hello.
I'm author of [`fbx_direct`](https://crates.io/crates/fbx_direct), which provides FBX parser and writer.
Recently I've been developing a new crate [`fbxcel`](https://crates.io/crates/fbxcel), which attempts to provide not only parser but also DOM-related features.

`fbx_direct` is quite low-level library (only event-based parser and writer!) and hard to use in game.
In contrast, `fbxcel` provides access to tree structure of FBX file, and I'm implementing features to access high-level structure of FBX data (such as bones, meshes, textures, etc...)
I recommend game developers to use `fbxcel` rather than `fbx_direct`.

**Comment by lo48576** [comment]
Situation updated:

I splitted fbxcel into low-level part and DOM part.
Just now I published [`fbxcel-dom`](https://crates.io/crates/fbxcel-dom) crate, which has DOM features.

Usual users (who want to render FBX) would need `fbxcel-dom` rather than `fbxcel`.

**Comment by doppioslash** [comment]
Added in df1432daeefab4e07f549ccb6f48c7b90a2ec0d7.
