### ISSUE TITLE
lyon crate doesn't exist anymore

### ISSUE THREAD

**Issue by killkrt** [doppioslash/arewegameyet#18]
Hi,

Just a little issue...
I've noticed that the inox crate linked [here](http://arewegameyet.com/categories/2drendering.html) seems to be not valid anymore and it seems to be disappeared completely from Git.

Thank you.

**Comment by doppioslash** [comment]
thanks, it's actually the inox github that is gone, got them switched by mistake.
I fixed the lyon github link, it should work now.

Not all crates have accurate repos on crates.io, they depend on the crate's maintainer.
