### ISSUE TITLE
Modify crate: uil

### ISSUE THREAD

**Issue by xavier83** [doppioslash/arewegameyet#19]
Please fix crate name in category: ui.
isn't it supposed to be [oil](http://oil-lang.github.io/). thanks.

**Comment by doppioslash** [comment]
Thanks, I'll fix it. But it is uil on the crates.io site.
If library authors don't keep their crates.io entry up-to-date we get wrong information.

**Comment by doppioslash** [comment]
ah, actually there is an oil crate too. Ok, moved uil to oil, since uil is an old version.
