### ISSUE TITLE
Broken navigation links outside of homepage

### ISSUE THREAD

**Issue by benfrankel** [doppioslash/arewegameyet#196]
**What is the issue?**

When you're on a page that isn't the homepage, the fixed navigation bar's links don't navigate anywhere. The links only work correctly on the homepage.

**Why does the issue occur?**

The fixed navigation bar uses relative links like `#chat`, and if you're on a page like `/categories/2drendering`, that resolves to `/categories/2drendering/#chat` which isn't a thing.

The issue doesn't occur for the top-of-page navigation bar because it uses absolute links like `/#chat`.

**Comment by benfrankel** [comment]
Also the Contact Us link in the footer is broken.

**Comment by doppioslash** [comment]
Odd, they are working fine for me. What browser/os are you on?

**Comment by benfrankel** [comment]
Huh, that's interesting. I'm on Firefox 67.0.4 on Arch Linux with kernel version 5.1.15-arch1-1-ARCH.

**Comment by benfrankel** [comment]
I just tried it on Chrome 75.0.3770.100 (64-bit) and had the same issue. Did you test it by scrolling down first and then using the fixed navigation bar in white?

**Comment by doppioslash** [comment]
If I remember right, yes I did.

**Comment by doppioslash** [comment]
Merged now, so I'm closing this but feel free to reopen as needed.
