### ISSUE TITLE
Links in the ecosystems section point to 127.0.0.1:1111 as the base URL.

### ISSUE THREAD

**Issue by simlay** [doppioslash/arewegameyet#199]
#### **What is the issue?**
The links on http://arewegameyet.com/#eco point to the wrong location.

#### **Expected functionality**
Links like this would point to 
http://arewegameyet.com/categories/2drendering/
rather than
http://127.0.0.1:1111/categories/2drendering/

**Comment by doppioslash** [comment]
Thanks, fixed
