### ISSUE TITLE
Add crate: vek (2D-3D math)

### ISSUE THREAD

**Issue by yoanlcq** [doppioslash/arewegameyet#70]
Some weeks ago I released [`vek 0.9`](https://github.com/yoanlcq/vek), a library crate tailored for gamedev-specific math foundations, with support for SIMD-enabled types.

This will obviously look biased, but I've been using it in my private student game project and so far it's been quite nice - I believe it is mature enough to be used in upcoming projects.

I'd be honored to have it mentioned in the "maths libs" section or Are We Game Yet. Thanks in advance!

**Comment by doppioslash** [comment]
Thanks! Added in commit b77f69f.
