### ISSUE TITLE
Add Vigilant Steel

### ISSUE THREAD

**Issue by ozkriff** [doppioslash/arewegameyet#79]
![](https://gitlab.com/remram44/vigilant-steel/raw/master/screenshot.png)

https://gitlab.com/remram44/vigilant-steel

https://www.reddit.com/r/rust/comments/83sygy/whats_everyone_working_on_this_week_112018/dvkwxm1/

> ([in-browser version](http://remram44.gitlab.io/vigilant-steel/) thanks to Emscripten; WASD/space).

**Comment by doppioslash** [comment]
Thanks. Fixed in commit bde5945.
