### ISSUE TITLE
Add Jakar-Engine

### ISSUE THREAD

**Issue by ozkriff** [doppioslash/arewegameyet#80]
https://github.com/SiebenCorgie/jakar-engine

> Formerly "Ori-Engine" is an hobby project of mine. Target is an Rust/Vulkan engine for games and visualization software.

Some videos:
- https://www.youtube.com/watch?v=nBDf6KpIBRw
- https://www.youtube.com/watch?v=FhV0eGdSGFY

**Comment by doppioslash** [comment]
Thanks! Fixed in commit 521e41b.
