### ISSUE TITLE
Improve the design of category pages

### ISSUE THREAD

**Issue by GloverDonovan** [doppioslash/arewegameyet#81]
This is how category pages currently look:

![https://i.imgur.com/uN4WbcT.jpg](https://i.imgur.com/uN4WbcT.jpg)

Some things I noticed:

1. The permalink isn't needed. Most people will just link to the project page instead.
2. The gitter blurb isn't needed. Most people will want the project page, and most projects don't use gitter.
3. The badges are OK, but aren't needed IMO (they also increase the load time). If I wanted to know more about a project, I'd visit its project page.
4. Some projects have insanely long descriptions, others have logos in odd spots; some use punctuation, others don't, etc. It'd be great if the presentation of these projects were standardized and made more consistent. [Example](https://github.com/github/explore/blob/master/docs/API.md).

Complaints on user experience:

- The title should be clickable. From an accessibility standpoint, the title describes the project and the project is linked to the title. Hiding this link behind a hard-to-click home icon isn't helpful.
- The icons need to be changed. They are small and hard to click. How about moving the icons to where the badges are instead, and adding text to them so that the links are larger and easier to click?

Any other suggestions are appreciated.

**Comment by doppioslash** [comment]
The long description generally comes from the crate description.
I don't agree with 1, 2,3 and 4.
The use of a website like this is having all info at a glance, without having to go to the project website.

But agree that the title should be clickable, and the icons could be bigger.

**Comment by GloverDonovan** [comment]
Sounds good to me. I was probably annoyed by how the badges were easier to click than the icons. I don't use them, but other users probably do, and we shouldn't needlessly take away existing features from end users.
