### ISSUE TITLE
Update URLs for sdl2 crate

### ISSUE THREAD

**Issue by ghost** [doppioslash/arewegameyet#84]
The github URL should be https://github.com/Rust-SDL2/rust-sdl2 
and the documentation URL should be https://crates.io/crates/sdl2/reverse_dependencies

Just doin' my duty ;)

**Comment by doppioslash** [comment]
Thanks. I think you meant https://rust-sdl2.github.io/rust-sdl2/sdl2/ for the docs.

**Comment by doppioslash** [comment]
Fixed in commit dddb767
