### ISSUE TITLE
Add Rostige Schlange (game)

### ISSUE THREAD

**Issue by Dooskington** [doppioslash/arewegameyet#89]
Rostige Schlange ("Rusty Snake" in German apparently) is just a small snake clone, using OpenGL for rendering. Thought it may be a good example and a valuable resource for beginners.

![Rostige Schlange](https://user-images.githubusercontent.com/4643504/41987803-1f74d5d4-79ef-11e8-9b69-da4a78480c82.png)

https://github.com/Dooskington/Rostige-Schlange

**Comment by doppioslash** [comment]
Thanks! Fixed in commit dddb767
