### ISSUE TITLE
Add crate: openvr

### ISSUE THREAD

**Issue by whentze** [doppioslash/arewegameyet#90]
The "VR" category lists https://github.com/lucidscape/openvr-rs, which has not seen any updates in 2+ years. There is a more popular and more recently updated crate, simply called "openvr" with high-level OVR bindings at https://github.com/rust-openvr/rust-openvr.

**Comment by doppioslash** [comment]
Thanks. This library is not on crates.io?

**Comment by doppioslash** [comment]
Fixed in commit dddb767
