### ISSUE TITLE
Add "HyperZen Training" game

### ISSUE THREAD

**Issue by ozkriff** [doppioslash/arewegameyet#97]
Source: https://twitter.com/232th/status/1030606503043059712

> I released hyperzen training on steam also (using winit, vulkano, specs, nphysics) even if I didn't talk about it https://store.steampowered.com/app/884160/HyperZen_Training/

> Experimental minimalist game with a special graphical mecanic.
The whole experience is supposed to let you focus on your targets. Allowing you to improve your skills without artifices.
>
> The gameplay is really about fast paced old FPS but with smaller targets and some kind of puzzle to understand and challenge the graphical mecanic.
Levels are mostly maze generated with procedural generation.

![image](https://user-images.githubusercontent.com/662976/44296598-b21ae280-a2ca-11e8-8253-9cebe5f12cd2.png)

**Comment by doppioslash** [comment]
Thanks! Fixed in commit dddb767
